version: 1
formatters:
  color:
    # Reference to the custom formatter class
    '()': pytower.logging.ColorFormatter
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: color
    stream: ext://sys.stdout
root:
  level: DEBUG
  handlers: [console]